### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by ekweible** [cferdinandi/atomic#10]
Any chance you could publish this to NPM? Looks like `atomic` is taken but `atomicjs` is available.

By the way thanks for making this!

**Comment by bradbenvenuti** [comment]
This is great. Would love to use it through npm also though.

**Comment by munkychop** [comment]
+1

**Comment by cferdinandi** [comment]
Just took this over from Todd, and will closing this issue down as wontfix. Allow me to explain why:

1. You can use npm (or you favorite package manager) [directly from GitHub](https://github.com/cferdinandi/atomic#installing-with-package-managers).
2. I manage several dozen OSS projects, and publishing to NPM adds an additional step for me.

Sorry!

**Comment by ben-eb** [comment]
I guess it isn't the resolution I wanted, but thanks for updating us. 😃 

By the way, I recommend https://github.com/sindresorhus/np for a much saner publish/test step.

**Comment by cferdinandi** [comment]
I know, sorry. =(

It's a personal sanity thing.

**Comment by munkychop** [comment]
This is disappointing. I'd hoped that I'd be able to hand over the `atomicjs` npm package to the original maintainer at some point.

And although I appreciate this is a personal choice, personally I don't think it's all that difficult to publish to npm – especially when so many people are interested in the project.

I'm very happy to contribute in this regard, if you need additional maintainers...

**Comment by cferdinandi** [comment]
Change of heart. I've decided to support this. Looks like I'm going to have to rename this project to support this, as `atomic` is already taken on NPM.

**Comment by munkychop** [comment]
@cferdinandi I have `atomicjs` and can give that up in favour of the original project, if you like?
If so, I suggest we collaborate to publish as a new major version, as there are some slight API differences between the two versions, IIRC

**Comment by cferdinandi** [comment]
Hey, absolutely. I've already made a major version jump. Happy to push that on NPM if you want to transfer it over.

**Comment by munkychop** [comment]
Great, I'll take a look at getting this sorted on the weekend, if I get the time.
I see you've added a way to set the `ContentType` header for each individual request, which is great. My version also has convenience methods for `get`, `post`, `put`, and `delete`, as well as a method – `setContentType` – to set the default content type for all subsequent requests. These may be something worth considering in your version too.

**Comment by cferdinandi** [comment]
@munkychop Your version is, I believe, a fork of 1.x, which had all of those features (https://github.com/cferdinandi/atomic/releases/tag/v1.2.0).

They went away in version 2.x in favor of a more flexible syntax that supports additional request types (for example `OPTIONS` or `CONNECT`) that were not supported in v1.

**Comment by munkychop** [comment]
Yeah, you're right about that, but it _would_ be nice to have a simple way to set the default content type. Anyways, I'll get the npm package name transferred to you soon, I've just been pretty swamped lately.

**Comment by willsteinmetz** [comment]
Hi guys, just bumping this to see if there is any status update. In my organizations infinite wisdom, they blocked us from being able to install npm packages using the github flag/ability (don't ask, I can't divulge details). However, things seem to still work properly if they are a regular npm module most likely because of the pass through with the NPM organization. Is there any chance the npm stuff is coming soon?

**Comment by cferdinandi** [comment]
@munkychop Still willing to transfer ownership to me? If so, I can initiate the request via NPM if you're unable to. Otherwise, I'm going to setup a new NPM repository for this.

**Comment by munkychop** [comment]
@cferdinandi after some reflection, I'm now thinking this may be a bad idea, since the npm package has quite a few people downloading the project regularly and so changing the underlying repo would break their builds, as any of the old versions defined in a `package.json` would no longer resolve.

If there is any way the guys at npm could rewire things to ensure the old versions would resolve, then I'd be more than happy to transfer over to you. I just don't want to put other developers in a bad situation.

Otherwise, if npm can't help with this, then publishing a scoped module could perhaps work well for you?

**Comment by willsteinmetz** [comment]
@munkychop Are you worrying about the repo URL changing and that breaking? If so, I wouldn't worry too if you use the GitHub project transfer functionality because it will create redirects. I've had to move projects before and all of the old URLs resolve to the new ones. ex: https://github.com/ralivue/notific8 goes to https://github.com/willsteinmetz/notific8

**Comment by cferdinandi** [comment]
@munkychop NPM caches their own version of the file and only uses package.json to set version numbers at time of publish. References to the old version number would load your old version. 

Ie. I've done this before. It'll be fine.

**Comment by munkychop** [comment]
@willsteinmetz actually the Github project isn't moving, since mine is a fork of the original; I was concerned about the npm package itself referencing a different repository.

@cferdinandi I see, that makes sense. I added you as a collaborator back in May...

**Comment by willsteinmetz** [comment]
My bad. I misunderstood what was being said.

**Comment by cferdinandi** [comment]
@munkychop I'm not sure that helps? Let me look, but I think we need to contact NPM about moving ownership of the name on NPM.

**Comment by cferdinandi** [comment]
Alright everyone, this is now officially on NPM. Super huge thanks to @munkychop for letting me take over the listing on NPM!
